dir_list:
  - { path: "/etc/docker", mode: "0755" }

copy_list:
  - { src: "{{ cache_dir }}/docker/docker",       dest: "/usr/bin",                 mode: "0755" }
  - { src: "{{ cache_dir }}/docker/dockerd",      dest: "/usr/bin",                 mode: "0755" }
  - { src: "{{ cache_dir }}/docker/docker-init",  dest: "/usr/bin",                 mode: "0755" }
  - { src: "{{ cache_dir }}/docker/docker-proxy", dest: "/usr/bin",                 mode: "0755" }
  - { src: "{{ cache_dir }}/docker-compose",      dest: "/usr/bin",                 mode: "0755" }
  - { src: "docker.service",                      dest: "/usr/lib/systemd/system",  mode: "0644" }
  - { src: "docker.socket",                       dest: "/usr/lib/systemd/system",  mode: "0644" }

templates:
  - { src: "daemon.json", dest: "/etc/docker/daemon.json",  mode: "0644" }

start_command:
  - getent group docker || groupadd docker
  - systemctl daemon-reload
  - systemctl enable docker
  - systemctl restart docker

check_app:
  - systemctl status docker
