data:
  operations:
    - name: install-cluster
      title:
        zh: 安装集群
        en: Install Cluster
      steps:
        - name: 01-init-os
          title:
            zh: 初始化操作系统
            en: Init Operating System
        - name: 02-install-cri
          title:
            zh: 安装容器运行时
            en: Install Container Runtime Engine
        - name: 03-install-etcd
          title:
            zh: 安装 ETCD
            en: Install ETCD
        - name: 04-install-k8s
          title:
            zh: 安装 K8S 控制节点
            en: Install Control Plane
        - name: 05-join-k8s
          title:
            zh: 安装 K8S 工作节点
            en: Install Node
    - name: add-node
      title:
        zh: 添加节点
        en: Add Node
      pangeecluster_node_action: add_node
      steps:
        - name: 01-init-os
          title:
            zh: 初始化操作系统
            en: Init Operating System
        - name: 02-install-cri
          title:
            zh: 安装容器运行时
            en: Install Container Runtime Engine
        - name: 03-join-k8s
          title:
            zh: 安装 K8S 工作节点
            en: Install Node
    - name: delete-node
      title:
        zh: 删除节点
        en: Delete Node
      pangeecluster_node_action: delete_node
      steps:
        - name: 01-remove-from-cluster
          title:
            zh: 从集群删除节点
            en: Remote Node from Cluster
        - name: 02-reset-node
          title:
            zh: 重置节点
            en: Reset Node
    - name: install-harbor
      title:
        zh: 安装Harbor
        en: Install Harbor
      steps:
        - name: 01-install-harbor
          title:
            zh: 安装 Harbor
            en: Install Harbor
  dependency:
    - name: kubernetes
      version: 1.28.15
      category: kubernetes
      artifact:
        type: "tarball"
        tarball_content_directory: kubernetes/server/bin/
        url:
          default: "https://dl.k8s.io/v${version}/kubernetes-server-${os}-${arch}.tar.gz"
        checksum:
          linux_arm64: sha256:86f75c82f434eb7e6ae07113f100cc0bc0e0fe05a5a7f7a423ed166a6ab525ae
          linux_amd64: sha256:1963a6a05976be5668e4e5173a6f28e409fddca3e9a0a1c2bdd7db1dd83faf8b
    - name: containerd
      version: 1.7.27
      category: container_runtime
      artifact:
        type: "tarball"
        tarball_content_directory: bin/
        url:
          default: "https://github.com/containerd/containerd/releases/download/v${version}/containerd-${version}-${os}-${arch}.tar.gz"
        checksum:
          linux_arm64: sha256:3f03ea60c7dacddf890be3ab18f7ef859d9d104b19627f52038d7984361912bc
          linux_amd64: sha256:5b038fb22ab5dbb1ce57dd3d8f102460cd8619ff2afc78870837b06e8c4e840a
    - name: runc
      version: 1.2.6
      category: container_runtime
      artifact:
        type: "binary"
        url:
          default: "https://github.com/opencontainers/runc/releases/download/v${version}/runc.${arch}"
        checksum:
          linux_arm64: sha256:12c612e2ebe6ca198de676ce75ed557e79fe6109032209bb8e25166c967fe170
          linux_amd64: sha256:0774f49d1b1eebb5849e644db5e4dc6f2b06cee05f13b3d17d5d6ba62d6f2ebc
    - name: nerdctl
      version: 1.7.7
      category: container_runtime
      artifact:
        type: "tarball"
        url:
          default: "https://github.com/containerd/nerdctl/releases/download/v${version}/nerdctl-${version}-${os}-${arch}.tar.gz"
        checksum:
          linux_arm64: sha256:230ad8f4f88100774d123213a427d3d43071e0dcf9f70efbea50ab9efff1cd4c
          linux_amd64: sha256:298bb95aee485b24d566115ef7e4e90951dd232447b05de5646a652a23db70a9
    - name: docker
      version: 28.0.4
      category: container_runtime
      artifact:
        type: "tarball"
        tarball_content_directory: docker/
        url:
          linux_arm64: "https://download.docker.com/${os}/static/stable/aarch64/docker-${version}.tgz"
          linux_amd64: "https://download.docker.com/${os}/static/stable/x86_64/docker-${version}.tgz"
        checksum:
          linux_arm64: sha256:d3291093e8ed576ed9e237b24dc4556a9ed21ff25d4c26578df612cb6fe0480f
          linux_amd64: sha256:6b130fa5fb13516620d5ece0b63f63a495cede428bb2f9e24449022e9d72e0cb
    - name: docker-compose
      version: 2.35.1
      category: container_runtime
      artifact:
        type: "binary"
        url:
          linux_arm64: "https://github.com/docker/compose/releases/download/v${version}/docker-compose-${os}-aarch64"
          linux_amd64: "https://github.com/docker/compose/releases/download/v${version}/docker-compose-${os}-x86_64"
        checksum:
          linux_arm64: sha256:a91e930a076b91e6c69f11d1dbe3c06729ae765fb9dbb3f97cb808e784647399
          linux_amd64: sha256:7bdb2ce2916e5dd0354e5d129892bf96fdcdb1a9ab8eed69b9173e131db4c230
    - name: etcd
      version: 3.5.21
      category: etcd
      artifact:
        type: "tarball"
        tarball_content_directory: etcd-v${version}-${os}-${arch}/
        url:
          default: "https://github.com/etcd-io/etcd/releases/download/v${version}/etcd-v${version}-${os}-${arch}.tar.gz"
        checksum:
          linux_arm64: sha256:95bf6918623a097c0385b96f139d90248614485e781ec9bee4768dbb6c79c53f
          linux_amd64: sha256:adddda4b06718e68671ffabff2f8cee48488ba61ad82900e639d108f2148501c
    - name: pause
      version: 3.8
      category: image
      artifact:
        type: "container_image"
        image:
          default: registry.k8s.io/pause:${version}
    - name: coredns
      version: 1.7.1
      category: image
      artifact:
        type: "container_image"
        image:
          default: coredns/coredns:${version}
    - name: keepalived
      version: 2.0.20
      category: image
      artifact:
        type: "container_image"
        pull_all_platforms: true
        image:
          default: osixia/keepalived:${version}
    - name: haproxy
      version: 2.2
      category: image
      artifact:
        type: "container_image"
        image:
          default: haproxy:${version}
    - name: calico-cni
      version: v3.23.2
      category: image
      artifact:
        type: "container_image"
        image:
          default: calico/cni:${version}
    - name: calico-node
      version: v3.23.2
      category: image
      artifact:
        type: "container_image"
        pull_all_platforms: true # 使用 nerdctl pull --platform linux/arm64 calico-node:v3.23.2 命令不能够成功拉取镜像。 配置 pull_all_platforms 为 true 时，将使用 nerdctl pull --all-platforms 命令
        image:
          default: calico/node:${version}
    - name: calico-kube-controllers
      version: v3.23.2
      category: image
      artifact:
        type: "container_image"
        image:
          default: calico/kube-controllers:${version}
    - name: goharbor-chartmuseum-photon
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/chartmuseum-photon:${version}
    - name: goharbor-harbor-core
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/harbor-core:${version}
    - name: goharbor-harbor-db
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        pull_all_platforms: true
        image:
          default: goharbor/harbor-db:${version}
    - name: goharbor-harbor-exporter
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/harbor-exporter:${version}
    - name: goharbor-harbor-jobservice
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/harbor-jobservice:${version}
    - name: goharbor-harbor-log
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        pull_all_platforms: true
        image:
          default: goharbor/harbor-log:${version}
    - name: goharbor-harbor-portal
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/harbor-portal:${version}
    - name: goharbor-harbor-registryctl
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/harbor-registryctl:${version}
    - name: goharbor-nginx-photon
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/nginx-photon:${version}
    - name: goharbor-notary-server-photon
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/notary-server-photon:${version}
    - name: goharbor-notary-signer-photon
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/notary-signer-photon:${version}
    - name: goharbor-prepare
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/prepare:${version}
    - name: goharbor-redis-photon
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/redis-photon:${version}
    - name: goharbor-registry-photon
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/registry-photon:${version}
    - name: goharbor-trivy-adapter-photon
      version: v2.5.5
      category: image
      artifact:
        type: "container_image"
        image:
          default: goharbor/trivy-adapter-photon:${version}
metadata:
  available_at:
    - registry.cn-shanghai.aliyuncs.com/pangee-cluster/pangee-cluster-resource
    - swr.cn-east-2.myhuaweicloud.com/kuboard/pangee-cluster-resource
    - eipwork/pangee-cluster-resource
  can_replace_to: null
  can_upgrade_from:
    exclude: null
    include:
      - spray-v2.21.0[a-c]_k8s-v1.26.[0-3]*_v4.[1-3]-amd64
      - spray-v2.20.0[a-b]_k8s-v1.25.[0-9]*_v3.[0-9]*-amd64
  issue_date: "2023-4-29"
  kuboard_spray_version:
    min: v1.2.4
  owner: shaohq@foxmail.com
  supported_feature:
    eviction_hard: true
  supported_os:
    - distribution: Ubuntu
      versions:
        - "20.04"
        - "22.04"
    - distribution: Anolis
      versions:
        - "8.4"
        - "8.5"
        - "8.6"
    - distribution: CentOS
      versions:
        - "7.6"
        - "7.8"
        - "7.9"
        - "8"
    - distribution: RedHat
      versions:
        - "7.9"
        - "8.5"
    - distribution: OracleLinux
      versions:
        - "8.5"
        - "8.7"
        - "9.1"
    - distribution: Rocky
      versions:
        - "8.5"
        - "8.7"
        - "9.1"
    - distribution: openEuler
      versions:
        - "20.03"
        - "22.03"
    - distribution: Kylin Linux Advanced Server
      versions:
        - V10
    - distribution: openSUSE Leap
      versions:
        - "15.3"
    - distribution: UnionTech OS Server 20
      versions:
        - "20"
    - distribution: AlmaLinux
      versions:
        - "8.7"
        - "9.1"
  type: pangee-cluster-resource-package
  version: pangee-cluster-1.28.15_v1
