- hosts: kube_node,kube_control_plane
  gather_facts: false
  tasks:
    - name: Group delete_node
      group_by:
        key: "delete_node"
      when: pangeecluster_node_action is defined and pangeecluster_node_action == 'delete_node'

- hosts:
    - kube_control_plane
  gather_facts: true
  roles:
    - role: kube-node-delete
      when: inventory_hostname == (groups['kube_control_plane'])[0]
