- name: Check kubernetes Status
  hosts: kube_control_plane
  gather_facts: False
  strategy: free
  tasks:
    - name: |
        name: node_status
        description:
          en: Check node status
          zh: 检查 node 状态
      shell: |+
        COUNT=$(kubectl get nodes | grep -c {{ hostvars[inventory_hostname]['ip'] }})
        if [ "$COUNT" == "0" ]; then
          echo "0"
        else
          kubectl get nodes | grep {{ hostvars[inventory_hostname]['ip'] }}
        fi
      when: inventory_hostname == (groups['kube_control_plane'])[0]
