- hosts:
    - kube_control_plane
  gather_facts: true
  roles:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- hosts:
    - kube_control_plane
  gather_facts: true
  roles:
    - kube-ha

- hosts:
    - kube_control_plane
  gather_facts: true
  roles:
    - kube-node
    - kube-label

- hosts:
    - kube_control_plane
  gather_facts: true
  roles:
    - role: calico
      when: inventory_hostname == (groups['kube_control_plane'])[0]
    - role: coredns
      when: inventory_hostname == (groups['kube_control_plane'])[0]
