- hosts: kube_node,kube_control_plane
  gather_facts: false
  tasks:
    - name: Group delete_node
      group_by:
        key: "delete_node"
      when: pangeecluster_node_action is defined and pangeecluster_node_action == 'delete_node'

- hosts:
    - delete_node
  gather_facts: true
  roles:
    - kube-node-disable
