copy_list:
  - { src: "{{ cache_dir }}/kubernetes/kube-controller-manager",  dest: "{{ root_dir }}/usr/bin", mode: "0755" }

templates:
  - { src: "controller-manager",              dest: "{{ kube_config_dir }}",    mode: "0644" }
  - { src: "kube-controller-manager.service", dest: "{{ root_dir }}/service",  mode: "0644" }

start_command:
  - ln -sf {{ root_dir }}/service/*.service /etc/systemd/system/
  - systemctl daemon-reload
  - systemctl restart kube-controller-manager
  - systemctl enable kube-controller-manager

check_app:
  - systemctl status kube-controller-manager
