- name: Get certificate authority data
  shell: cat {{ certs_dir }}/ca.crt | base64 -w 0
  register: ca_crt_data
  delegate_to: localhost

- name: Get client certificate data
  shell: cat {{ certs_dir }}/client.crt | base64 -w 0
  register: client_crt_data
  delegate_to: localhost

- name: Get client key data
  shell: cat {{ certs_dir }}/client.key | base64 -w 0
  register: client_key_data
  delegate_to: localhost

- name: set fact
  set_fact:
    "{{ item.var }}": "{{ item.value }}"
  loop: "{{ set_facts }}"
  when: set_facts is defined

- name: Create directories
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode | default(omit) }}"
    state: "{{ item.state | default('directory') }}"
  loop: "{{ dir_list }}"
  when: dir_list is defined

- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ copy_list }}"
  when: copy_list is defined

- name: Copy template
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ templates }}"
  when: templates is defined

- name: Install
  shell: "{{ item }}"
  loop: "{{ start_command }}"
  loop_control:
    label: "{{ item }}"
  when: start_command is defined

- name: Check application
  shell: "{{ item }}"
  loop: "{{ check_app }}"
  loop_control:
    label: "{{ item }}"
  when: check_app is defined
  register: result
  until: result.rc == 0
  retries: "{{ check_app_retries | default('30') | int }}"
  delay: "{{ check_app_delay | default('1') | int }}"
