- name: set fact
  set_fact:
    "{{ item.var }}": "{{ item.value }}"
  loop: "{{ set_facts }}"
  when: set_facts is defined

- name: Install
  shell: "{{ item }}"
  loop: "{{ start_command }}"
  loop_control:
    label: "{{ item }}"
  when: start_command is defined

- name: Set sysctl.conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop: "{{ kernel_option }}"
  loop_control:
    label: "{{ item.name }}"
  when: kernel_option is defined

- name: Set limits.conf
  pam_limits:
    dest: "{{ item.dest }}"
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  loop: "{{ limits_list }}"
  when: limits_list is defined

- name: Line in file
  lineinfile:
    dest: "{{ item.file }}"
    regexp: "{{ item.regexp | default('___impossible_pattern___') }}"
    line: "{{ item.line | default(None) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ line_list }}"
  when: line_list is defined

- name: Block in file
  blockinfile:
    path: "{{ item.file }}"
    marker: "{{ item.marker }}"
    block: "{{ item.block }}"
  loop: "{{ block_list }}"
  when: block_list is defined
